package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.Supplier;

import org.littletonrobotics.junction.Logger;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.configs.Pigeon2Configuration;
import com.ctre.phoenix6.hardware.CANcoder;
import com.ctre.phoenix6.hardware.Pigeon2;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;

import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;

import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.Nat;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.estimator.SwerveDrivePoseEstimator;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.kinematics.SwerveDriveKinematics;
import edu.wpi.first.math.kinematics.SwerveDriveOdometry;
import edu.wpi.first.math.kinematics.SwerveModulePosition;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.networktables.DoublePublisher;
import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableEntry;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.networktables.StructPublisher;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.CommandScheduler;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.LimelightHelpers;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class SS_Drivetrain extends TunerSwerveDrivetrain implements Subsystem {
    public CANBus canivore = new CANBus("rio");
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;
    public final Pigeon2 pidgey = new Pigeon2(0);
    public Pigeon2Configuration pigeonConfig = new Pigeon2Configuration();

    public boolean targetToggled = false;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.kZero; //k180deg
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    /** Swerve request to apply during robot-centric path following */
    private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    public SwerveDriveKinematics kinematics = new SwerveDriveKinematics(new Translation2d[] {
        new Translation2d(Inches.of(10), Inches.of(10)),
        new Translation2d(Inches.of(10), Inches.of(-10)),
        new Translation2d(Inches.of(-10), Inches.of(10)),
        new Translation2d(Inches.of(-10), Inches.of(-10))
    });
    
    public SwerveModulePosition[] modulePositions = new SwerveModulePosition[] {
        getModule(0).getPosition(true),
        getModule(1).getPosition(true),
        getModule(2).getPosition(true),
        getModule(3).getPosition(true)
    };

    // public SwerveDriveOdometry poseOdometry = new SwerveDriveOdometry(
    //     kinematics, 
    //     kBlueAlliancePerspectiveRotation, 
    //     modulePositions,
    //     new Pose2d(4.625594, 3.043936, new Rotation2d(0))
    // );

    public SwerveDrivePoseEstimator poseEstimator = new SwerveDrivePoseEstimator(
        kinematics, 
        kBlueAlliancePerspectiveRotation,
        modulePositions, 
        new Pose2d(0.4318, 4.021328, new Rotation2d(0)), 
        new Matrix<N3, N1>(Nat.N3(), Nat.N1(), new double[] {0.2, 0.2, 0.2}), 
        new Matrix<N3, N1>(Nat.N3(), Nat.N1(), new double[] {0.6, 0.6, 0.5})
    );

    // Poses for AdvantageScope
    Pose2d robotPoseEstimate;
    // Pose2d robotOdoPose;
    Pose2d robotLLPoseAntigua;
    Pose2d robotLLPoseBarbuda;
    
    // Fields for AdvantageScope
    Field2d estimatedField = new Field2d();
    Field2d limelightFieldBarbuda = new Field2d();
    Field2d limelightFieldAntigua = new Field2d();
    // Field2d odometryField = new Field2d();
    Field2d targetField = new Field2d();

    // Limelight Estimation
    public NetworkTableInstance inst = NetworkTableInstance.getDefault();
    NetworkTable limelightTableAntigua = inst.getTable("limelight-antigua");
    NetworkTable limelightTableBarbuda = inst.getTable("limelight-barbuda");
    double[] limelightEstimateAntigua = new double[6];
    double[] limelightEstimateBarbuda = new double[6];
    double stdDev;

    // Gyro Stuff
    Rotation2d gyroAngle;
    double gyroSpeed;
    
    // Swerve Modules
    SwerveModule<TalonFX, TalonFX, CANcoder> module0 = getModule(0);
    SwerveModule<TalonFX, TalonFX, CANcoder> module1 = getModule(1);
    SwerveModule<TalonFX, TalonFX, CANcoder> module2 = getModule(2);
    SwerveModule<TalonFX, TalonFX, CANcoder> module3 = getModule(3);
    
    // Potential Targets
    public Translation2d hubPose = new Translation2d(4.625594, 4.034536);
    public Translation2d towerPose = new Translation2d(1.7113, 4.134044);
    public Translation2d depotPose = new Translation2d(0.5, 6.391656);
    public Translation2d stationPose = new Translation2d(0.5, 1.651);

    // Chosen Target
    public Translation2d targetPose = hubPose;
    public Translation2d neutralTarget = towerPose;

    public DriverStation.Alliance alliance;

    public double orientationShift = 0;

    public double aimingAngle = 0;

    double basisX;
    double basisY;

    double xSpeed;
    double ySpeed;

    public double aimingComponent;
    public double driftingComponent;

    public NetworkTableEntry driveOn = inst.getTable("Drivetrain").getEntry("drivetrain");

    public enum ShootMode {
        SCORE,
        LOB
    }

    public ShootMode mode = ShootMode.SCORE;

    // Other Network Table Stuff
    NetworkTable shooter = NetworkTableInstance.getDefault().getTable("Shooter");
    NetworkTable poseTable = NetworkTableInstance.getDefault().getTable("Estimations");
    public NetworkTableEntry poseEstimatorEntry = poseTable.getEntry("Pose Estimator");
    public StructPublisher<Pose2d> posePublisher;

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
        new SysIdRoutine.Config(
            /* This is in radians per second², but SysId only supports "volts per second" */
            Volts.of(Math.PI / 6).per(Second),
            /* This is in radians per second, but SysId only supports "volts" */
            Volts.of(Math.PI),
            null, // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
            },
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public SS_Drivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) { 
        super(drivetrainConstants, modules); 
        if (Utils.isSimulation()) {
            startSimThread();
        }
        driveOn.setBoolean(true);
        configureAutoBuilder();
    }


    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public SS_Drivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        driveOn.setBoolean(true);
        applyRequest(null).execute();
        configureAutoBuilder();
        posePublisher = poseTable.getStructTopic("Pose Estimator", Pose2d.struct).publish();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public SS_Drivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    private void configureAutoBuilder() {
        try {
            var config = RobotConfig.fromGUISettings();
            AutoBuilder.configure(
                () -> getState().Pose,   // Supplier of current robot pose
                this::resetPose,         // Consumer for seeding pose against auto
                () -> getState().Speeds, // Supplier of current robot speeds
                // Consumer of ChassisSpeeds and feedforwards to drive the robot
                (speeds, feedforwards) -> setControl(
                    m_pathApplyRobotSpeeds.withSpeeds(ChassisSpeeds.discretize(speeds, 0.020))
                        .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                        .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())
                ),
                new PPHolonomicDriveController(
                    // PID constants for translation
                    new PIDConstants(10, 0, 0),
                    // PID constants for rotation
                    new PIDConstants(7, 0, 0)
                ),
                config,
                // Assume the path needs to be flipped for Red vs Blue, this is normally the case
                () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
                this // Subsystem for requirements
            );
        } catch (Exception ex) {
            DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
        }
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */

    public SwerveRequest idleRequest = new SwerveRequest.Idle();

    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> {
            if(driveOn.getBoolean(false))
            {
                this.setControl(request.get()); 
                System.out.println("Apply Request"); 
            }
            else
            {
                this.setControl(idleRequest); 
                System.out.println("Idling");
            }
        });
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override
    public void periodic() {
        Logger.recordOutput("Field", poseEstimator.getEstimatedPosition());
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }

        alliance = DriverStation.getAlliance().get();

        switch (alliance) {
            case Red:
                limelightEstimateAntigua = limelightTableAntigua.getEntry("botpose_orb_wpired").getDoubleArray(limelightEstimateAntigua);
                limelightEstimateBarbuda = limelightTableBarbuda.getEntry("botpose_orb_wpired").getDoubleArray(limelightEstimateBarbuda);
                break;
            case Blue:
                limelightEstimateAntigua = limelightTableAntigua.getEntry("botpose_orb_wpiblue").getDoubleArray(limelightEstimateAntigua);
                limelightEstimateBarbuda = limelightTableBarbuda.getEntry("botpose_orb_wpiblue").getDoubleArray(limelightEstimateBarbuda);
                break;
        }

        // Refresh module positions
        modulePositions[0] = module0.getPosition(true);
        modulePositions[1] = module1.getPosition(true);
        modulePositions[2] = module2.getPosition(true);
        modulePositions[3] = module3.getPosition(true);

        // Update gyro values
        Rotation2d gyroAngle = pidgey.getRotation2d();
        poseEstimator.update(gyroAngle, modulePositions);
        // poseOdometry.update(gyroAngle, modulePositions);
        
        robotPoseEstimate = poseEstimator.getEstimatedPosition();

        if (robotPoseEstimate.getY() > 4.034663) {
            neutralTarget = depotPose;
        } else {
            neutralTarget = stationPose;
        }

        if (robotPoseEstimate.getX() > 4.7) {
            targetPose = neutralTarget;
            mode = ShootMode.LOB;
        } else {
            targetPose = hubPose;
            mode = ShootMode.SCORE;
        }

        robotLLPoseAntigua = new Pose2d(limelightEstimateAntigua[0], limelightEstimateAntigua[1], new Rotation2d(Math.PI*limelightEstimateAntigua[5]/180));
        robotLLPoseBarbuda = new Pose2d(limelightEstimateBarbuda[0], limelightEstimateBarbuda[1], new Rotation2d(Math.PI*limelightEstimateBarbuda[5]/180));
        // robotOdoPose = poseOdometry.getPoseMeters();

        updateVisionFromLimelight("limelight-barbuda");
        updateVisionFromLimelight("limelight-antigua");

        //Put the poses on the fields
        estimatedField.setRobotPose(robotPoseEstimate);
        limelightFieldAntigua.setRobotPose(robotLLPoseAntigua);
        limelightFieldBarbuda.setRobotPose(robotLLPoseBarbuda);
        // odometryField.setRobotPose(robotOdoPose);
        targetField.setRobotPose(new Pose2d(targetPose, new Rotation2d(0)));

        //Add stuff to SmartDashboard
        SmartDashboard.putData("poseField", estimatedField);
        Logger.recordOutput("poseField", robotPoseEstimate);
        SmartDashboard.putData("limelightFieldAntigua", limelightFieldAntigua);
        Logger.recordOutput("limelightFieldAntigua", robotLLPoseAntigua);
        SmartDashboard.putData("limelightFieldBarbuda", limelightFieldBarbuda);
        Logger.recordOutput("limelightFieldBarbuda", robotLLPoseBarbuda);
        SmartDashboard.putData("targetField", targetField);
        Logger.recordOutput("targetField", new Pose2d(targetPose, new Rotation2d(0)));
        SmartDashboard.putNumber("pidgeonYaw", pidgey.getYaw().getValueAsDouble());
        Logger.recordOutput("pidgeonYaw", pidgey.getYaw().getValueAsDouble());
        SmartDashboard.putNumber("drivetrainYaw", this.getState().Pose.getRotation().getDegrees());
        Logger.recordOutput("drivetrainYaw", this.getState().Pose.getRotation().getDegrees());
        SmartDashboard.putString("shootMode", mode.name());
        Logger.recordOutput("shootMode", mode.name());
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    private void updateVisionFromLimelight(String limelightName) {
        switch (alliance) {
            case Blue:
                orientationShift = 0;
                break;
            case Red:
                orientationShift = 180;
                break;
        }
        LimelightHelpers.SetRobotOrientation(limelightName, 
            pidgey.getRotation2d().getDegrees() + orientationShift,
            pidgey.getAngularVelocityZDevice().getValueAsDouble(), 0, 0, 0, 0);
        LimelightHelpers.PoseEstimate mt2 = null;
        switch (alliance) {
            case Blue:
                mt2 = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2(limelightName);
            break;
            case Red:
                mt2 = LimelightHelpers.getBotPoseEstimate_wpiRed_MegaTag2(limelightName);
            break;
        }
        if (mt2 == null || mt2.tagCount == 0) return;
        if (Math.abs(pidgey.getAngularVelocityZDevice().getValueAsDouble()) > 720) return; // Reject during fast rotation
        
        stdDev = MathUtil.clamp(1.1*mt2.avgTagDist/mt2.tagCount, 0.35, 1.1);
        poseEstimator.setVisionMeasurementStdDevs(VecBuilder.fill(stdDev, stdDev, 0.5));
        // Use the vision translation but prefer the Pigeon/IMU for robot heading.
        // Vision headings can be noisy or use a different convention and were
        // overwriting the estimator's heading, causing the rotated localization.
        Pose2d visionPoseUsingGyroHeading = new Pose2d(mt2.pose.getTranslation(), pidgey.getRotation2d());
        poseEstimator.addVisionMeasurement(visionPoseUsingGyroHeading, mt2.timestampSeconds);
    }

    public void pigeonCommand() {
        pidgey.setYaw(0);
    }

    public void updateAligningAngle() {
        aimingAngle = poseEstimator.getEstimatedPosition().getTranslation().minus(targetPose).getAngle().getRadians() + pidgey.getRotation2d().getRadians();
    }

    public void calculateAimingVector() {
        updateAligningAngle();
        basisX = Math.cos(aimingAngle);
        basisY = Math.sin(aimingAngle);

        xSpeed = getState().Speeds.vxMetersPerSecond;
        ySpeed = getState().Speeds.vyMetersPerSecond;

        aimingComponent = basisX*xSpeed + basisY*ySpeed;

        SmartDashboard.putNumber("aimingComponent", aimingComponent);
    }

    public void calculateDriftingVector() {
        updateAligningAngle();
        basisX = Math.cos(aimingAngle + Math.PI/2);
        basisY = Math.sin(aimingAngle + Math.PI/2);

        xSpeed = getState().Speeds.vxMetersPerSecond;
        ySpeed = getState().Speeds.vyMetersPerSecond;

        driftingComponent = basisX*xSpeed + basisY*ySpeed;

        SmartDashboard.putNumber("driftingComponent", aimingComponent);
    }

    public double PoseEstimaterGetX()
    {
        return robotPoseEstimate.getX();
    }
}
